// // SHIPMENTS
export const UPDATE_SHIPMENTS_PROPS = "UPDATE_SHIPMENTS_PROPS";
export const MERGE_SHIPMENTS_PROPS = "MERGE_SHIPMENTS_PROPS";
export const DELETE_SHIPMENTS_PROPS = "DELETE_SHIPMENTS_PROPS";
export const CLEAR_SHIPMENTS_STATE = "CLEAR_SHIPMENTS_STATE";
