export const ar = {
  lang: "ar",
  ShipmentNumber: "رقم الشحنة",
  LastUpdated: "اخر تحديث",
  Monday: "الاثنين",
  Tuesday: "الثلاثاء",
  Wednesday: "الاربعاء",
  Thursday: "الخميس",
  Friday: "الجمعة",
  Saturday: "السبت",
  Sunday: "الاحد",
  at: " في ",
  SellerName: "اسم التاجر",
  DeliveryTimeWithin: "موعد التسليم خلال",
  January: " يناير ",
  ShipmentDelivered: "تم تسليم الشحنة",
  ShipmentDelivered2: "تم التسليم",
  ShipmentCancelled: "تم الغاء الشحنة",
  ShipmentCreated: "تم انشاء الشحنة",
  ShipmentReceived: "تم استلام الشحنة من التاجر",
  ShipmentOutDelivery: "الشحنة خرجت للتسليم",
  Branch: "الفرع",
  Date: "التاريخ",
  Time: "الوقت",
  Details: "التفاصيل",
  Lang: "ENG",
  TrackShipment: "تتبع شحنتك",
  SignIn: "تسجيل الدخول",
  Home: "الصفحة الرئيسية",
  Prices: "الاسعار",
  ContactUs: "تواصل معانا",
  EnterShipmentNumber: "اكتب رقم الشحنة وتابع شحنتك خطوة بخطوة",
  ShipmentDetails: "تفاصيل الشحنة",
  DeliveryAddress: "عنوان التسليم",
  ShipmentProblem: "هل يوجد مشكلة في شحنتك ؟",
  ReportProblem: "ابلاغ عن مشكلة",
  Shipments: "الشحنات",
  OurPricing: "الاسعار",
  AboutUs: "عن بوسطة",
  PrivacyPolicy: "سياسة الخصوصية",
  TermsConditions: "الشروط والأحكام",
  EnterShipmentId: "اكتب رقم الشحنة أو اختار",
  ShipmentNotDelivered: "لم يتم تسليم الشحنة ",
  ShipmentCanceledBySender: "تم الغاء الشحنة من التاجر",
};
