export const en = {
  lang: "en",
  ShipmentNumber: "Shipment Number",
  LastUpdated: "LastUpdated",
  Monday: "Monday",
  Tuesday: "Tuesday",
  Wednesday: "Wednesday",
  Thursday: "Thursday",
  Friday: "Friday",
  Saturday: "Saturday",
  Sunday: "Sunday",
  at: " at ",
  SellerName: "Seller Name",
  DeliveryTimeWithin: "Delivery Time Within",
  January: " January ",
  ShipmentDelivered: "Shipment Delivered",
  ShipmentDelivered2: "Shipment Delivered",
  ShipmentCancelled: "Shipment Cancelled",
  ShipmentCreated: "Shipment Created",
  ShipmentReceived: "Shipment Received from Seller",
  ShipmentOutDelivery: "The Shipment is out for Delivery",
  Branch: "Branch",
  Date: "Date",
  Time: "Time",
  Details: "Details",
  Lang: "عربي",
  SignIn: "Sign in",
  TrackShipment: "Track Shipment",
  Home: "Home",
  Prices: "Prices",
  ContactUs: "Contact Us",
  EnterShipmentNumber:
    "Enter the shipment number and follow your shipment step by step",
  ShipmentDetails: "Shipment Details",
  DeliveryAddress: "Delivery Address",
  ShipmentProblem: "Is there a problem with your shipment?",
  ReportProblem: "Report a Problem",
  Shipments: "Shipments",
  OurPricing: "Our Pricing",
  AboutUs: "About Us",
  PrivacyPolicy: "Privacy Policy",
  TermsConditions: "Terms and Conditions",
  EnterShipmentId: "Enter Shipment Number or Select it",
  ShipmentNotDelivered: "Shipment not delivered",
  ShipmentCanceledBySender: "The Shipment has been Canceled by the Sender",
};
